# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: step2.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'step2.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import alpha_pb2 as alpha__pb2
import beta_pb2 as beta__pb2
import gamma_pb2 as gamma__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstep2.proto\x12\x04vers\x1a\x0b\x61lpha.proto\x1a\nbeta.proto\x1a\x0bgamma.proto\"Y\n\x05\x44\x61ta2\x12\x1a\n\x05\x61lpha\x18\x01 \x01(\x0b\x32\x0b.vers.Alpha\x12\x18\n\x04\x62\x65ta\x18\x02 \x01(\x0b\x32\n.vers.Beta\x12\x1a\n\x05gamma\x18\x03 \x01(\x0b\x32\x0b.vers.Gammab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'step2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATA2']._serialized_start=59
  _globals['_DATA2']._serialized_end=148
# @@protoc_insertion_point(module_scope)
